#!/usr/bin/env python3
"""Generate the installer's shell package map from its YAML source."""

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts" / "distro-package-map.yaml"
TARGET = ROOT / "install.d" / "package_map.sh"
REQUIRED_DISTRIBUTIONS = {
    "alpine",
    "arch",
    "debian_12",
    "debian_13_plus",
    "fedora",
    "gentoo",
    "mageia",
    "solus",
    "suse",
    "ubuntu",
    "void",
}
LIST_FIELDS = {
    "appindicator",
    "gi_development",
    "optional_system",
    "python_suffixes",
    "shader_compiler",
    "system",
    "vulkan",
}
TEXT_TOOLS = {"wtype", "xdotool", "ydotool"}


def _package_list(value: Any, location: str, *, required: bool = False) -> list[str]:
    """Validate and return one package list."""
    if value is None and not required:
        return []
    if not isinstance(value, list) or (required and not value):
        raise ValueError(f"{location} must be a non-empty list")
    if any(not isinstance(item, str) or not item for item in value):
        raise ValueError(f"{location} must contain non-empty strings")
    if len(value) != len(set(value)):
        raise ValueError(f"{location} contains duplicate packages")
    return value


def load_map() -> dict[str, dict[str, Any]]:
    """Load and validate the authoritative YAML package map."""
    document = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(document, dict) or document.get("schema_version") != 1:
        raise ValueError("distro package map must use schema_version: 1")
    distributions = document.get("distributions")
    if not isinstance(distributions, dict):
        raise ValueError("distro package map must define a distributions mapping")
    names = set(distributions)
    if names != REQUIRED_DISTRIBUTIONS:
        missing = ", ".join(sorted(REQUIRED_DISTRIBUTIONS - names)) or "none"
        extra = ", ".join(sorted(names - REQUIRED_DISTRIBUTIONS)) or "none"
        raise ValueError(f"distribution keys differ (missing: {missing}; extra: {extra})")

    for distro, config in distributions.items():
        if not isinstance(config, dict):
            raise ValueError(f"distributions.{distro} must be a mapping")
        unknown = set(config) - LIST_FIELDS - {"text_input"}
        if unknown:
            raise ValueError(f"distributions.{distro} has unknown fields: {sorted(unknown)}")
        _package_list(config.get("system"), f"distributions.{distro}.system", required=True)
        for field in LIST_FIELDS - {"system"}:
            _package_list(config.get(field), f"distributions.{distro}.{field}")
        text_input = config.get("text_input")
        if not isinstance(text_input, dict) or set(text_input) != TEXT_TOOLS:
            raise ValueError(f"distributions.{distro}.text_input must define {sorted(TEXT_TOOLS)}")
        for tool in TEXT_TOOLS:
            _package_list(
                text_input.get(tool),
                f"distributions.{distro}.text_input.{tool}",
                required=True,
            )

    for distro in ("ubuntu", "fedora", "arch"):
        if len(distributions[distro].get("appindicator", [])) != 2:
            raise ValueError(f"distributions.{distro}.appindicator must define two fallbacks")
    if len(distributions["ubuntu"].get("gi_development", [])) != 2:
        raise ValueError("distributions.ubuntu.gi_development must define modern and legacy")
    for distro in ("ubuntu", "debian_12", "debian_13_plus"):
        if len(distributions[distro].get("shader_compiler", [])) < 2:
            raise ValueError(f"distributions.{distro}.shader_compiler needs a fallback")
    expected_suse_suffixes = [
        "pip",
        "gobject",
        "gobject-cairo",
        "devel",
        "virtualenv",
        "venv",
    ]
    if distributions["suse"].get("python_suffixes") != expected_suse_suffixes:
        raise ValueError("distributions.suse.python_suffixes has an unsupported order")
    return distributions


def _array_assignment(name: str, values: list[str], indent: str = "            ") -> str:
    quoted = " ".join(shlex.quote(value) for value in values)
    return f"{indent}{name}=({quoted})"


def render(distributions: dict[str, dict[str, Any]]) -> str:
    """Render a deterministic Bash module from the validated map."""
    lines = [
        "#!/bin/bash",
        "# Generated by scripts/generate_distro_package_map.py -- do not edit.",
        "# Regenerate with `just distro-packages` after editing",
        "# scripts/distro-package-map.yaml.",
        "",
        "load_distro_package_map() {",
        '    local package_map_key="$1"',
        "",
        "    SYSTEM_PACKAGES=()",
        "    APPINDICATOR_PACKAGES=()",
        "    GI_DEVELOPMENT_PACKAGES=()",
        "    OPTIONAL_SYSTEM_PACKAGES=()",
        "    PYTHON_PACKAGE_SUFFIXES=()",
        "    SHADER_COMPILER_PACKAGES=()",
        "    VULKAN_PACKAGES=()",
        "    XDOTOOL_PACKAGES=()",
        "    WTYPE_PACKAGES=()",
        "    YDOTOOL_PACKAGES=()",
        "",
        '    case "$package_map_key" in',
    ]
    names = {
        "system": "SYSTEM_PACKAGES",
        "appindicator": "APPINDICATOR_PACKAGES",
        "gi_development": "GI_DEVELOPMENT_PACKAGES",
        "optional_system": "OPTIONAL_SYSTEM_PACKAGES",
        "python_suffixes": "PYTHON_PACKAGE_SUFFIXES",
        "shader_compiler": "SHADER_COMPILER_PACKAGES",
        "vulkan": "VULKAN_PACKAGES",
    }
    for distro, config in distributions.items():
        lines.append(f"        {distro})")
        for field, variable in names.items():
            values = _package_list(config.get(field), f"{distro}.{field}")
            if values:
                lines.append(_array_assignment(variable, values))
        text_input = config["text_input"]
        lines.append(_array_assignment("XDOTOOL_PACKAGES", text_input["xdotool"]))
        lines.append(_array_assignment("WTYPE_PACKAGES", text_input["wtype"]))
        lines.append(_array_assignment("YDOTOOL_PACKAGES", text_input["ydotool"]))
        lines.extend(["            ;;", ""])
    lines.extend(
        [
            "        *)",
            '            echo "Unknown distro package map key: $package_map_key" >&2',
            "            return 1",
            "            ;;",
            "    esac",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Generate the map, or check that the committed output is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = parser.parse_args()
    try:
        generated = render(load_map())
    except (OSError, ValueError, yaml.YAMLError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != generated:
            print(
                f"{TARGET.relative_to(ROOT)} is stale; run `just distro-packages`",
                file=sys.stderr,
            )
            return 1
        return 0

    TARGET.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
